# allow ingress to `nekit-dev`
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-ingress-dev
  namespace: nekit
spec:
  podSelector:
    matchLabels:
      app: nekit-dev
  policyTypes:
    - Ingress
  ingress:
    - from: []
      ports:
        - protocol: TCP
          port: {{ .Values.dev.port }}
---
# allow ingress to `nekit-serve`
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-ingress-serve
  namespace: nekit
spec:
  podSelector:
    matchLabels:
      app: nekit-serve
  policyTypes:
    - Ingress
  ingress:
    - from: []
      ports:
        - protocol: TCP
          port: {{ .Values.serve.port }}
---
# allow ingress to `nekit-battery`
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-ingress-battery
  namespace: nekit
spec:
  podSelector:
    matchLabels:
      app: nekit-battery
  policyTypes:
    - Ingress
  ingress:
    - from: []
      ports:
        - protocol: TCP
          port: {{ .Values.battery.port }}
