name: pi

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - "**"

jobs:
  build:
    runs-on: ubuntu-26.04-arm
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup Nix
        uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
          extra_nix_config: |
            accept-flake-config = true
            trusted-users = root runner

      - name: Setup Cachix
        uses: cachix/cachix-action@v17
        with:
          name: nekitbot-pi
          authToken: ${{ secrets.CACHIX_BOT_TOKEN }}

      # - name: Connect to Tailscale
      #   uses: tailscale/github-action@v4
      #   with:
      #     oauth-client-id: ${{ secrets.TAILSCALE_OAUTH_CLIENT_ID }}
      #     oauth-secret: ${{ secrets.TAILSCALE_OAUTH_SECRET }}
      #     tags: tag:ci

      - name: Build
        run: nix build --print-build-logs .#nixosConfigurations.pi.config.system.build.toplevel

      # - name: Copy
      #   run: nix copy --to ssh://root@pi-installer?remote-store=/mnt/nix/store ./result
